apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: auto-study-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auto-study-backend
  template:
    metadata:
      labels:
        app: auto-study-backend
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: auto-study-app-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

